### ISSUE TITLE
Cant change user and password

### ISSUE THREAD

**Issue by nelbs** [sanderdw/hassio-addons#11]
I got a notification that the default credentials (admin and admin) are unsafe. I tried to change them in the addon configuration and the dsmr reader UI but after a restart they are reset to the default values

![image](https://user-images.githubusercontent.com/6464671/110204820-6e325d80-7e75-11eb-8d39-f93eff20c7ee.png)

**Comment by sanderdw** [comment]
Hi, you only need to change the DSMRREADER_ADMIN_PASSWORD in the Configuration tab. The addon will then change the password in the application:
![image](https://user-images.githubusercontent.com/19476345/110206619-0f71e180-7e7f-11eb-9cf0-a7dff2ef2def.png)

**Comment by nelbs** [comment]
Thanks, I accidentally pressed the wrong ok button 😄 
Now it works
