### ISSUE TITLE
Backup creation failed, please check the dsmr_backend logfile.

### ISSUE THREAD

**Issue by riddertommie** [sanderdw/hassio-addons#12]
Hi i did install your add-on of DSMR reader > Home Assistant Add-on: DSMR Reader, great plugin thanks!

No ones a day i get > Backup creation failed, please check the dsmr_backend logfile. (i don't know where to find that log)

this in unread notification in the dsmr tool itself, what's somewhat odd because if i look at the directory via SMB there is are files like dsmrreader-postgresql-backup-Friday.sql.gz in there.

Did i do something wrong? any tips hints?

Thanks

**Comment by sanderdw** [comment]
What set-up do you have?

**Comment by riddertommie** [comment]
I'm using Home Assistant Supervised on a rpi4 > i saw your there is a update i will do that first. will let you know.

**Comment by riddertommie** [comment]
Upgrading did the trick, did not see the error again.

Thanks!
