### ISSUE TITLE
Can't install DSMR Data logger

### ISSUE THREAD

**Issue by ymestechwey** [sanderdw/hassio-addons#13]
When i'm trying to install in Hassio the DSMR Data logger it fails.
It returns the next error: 

`21-03-26 14:21:28 INFO (SyncWorker_3) [supervisor.docker.addon] Starting build for 0826754b/armv7-addon-dsmr_datalogger:1.0.2
21-03-26 14:21:35 ERROR (SyncWorker_3) [supervisor.docker.addon] Can't build 0826754b/armv7-addon-dsmr_datalogger:1.0.2: The command '/bin/ash -o pipefail -c pip install --no-cache-dir -r requirements.txt' returned a non-zero code: 1
21-03-26 14:21:35 ERROR (SyncWorker_3) [supervisor.docker.addon] Build log: 
Step 1/16 : ARG BUILD_FROM

Step 2/16 : FROM $BUILD_FROM

 ---> e9ca1b7a326f

Step 3/16 : ENV LANG C.UTF-8

 ---> Using cache

 ---> 941b07890057

Step 4/16 : COPY run.sh /

 ---> Using cache

 ---> 47ec96c9fa2b

Step 5/16 : COPY dsmr_datalogger_api_client.py ./

 ---> Using cache

 ---> a88da3e8db1e

Step 6/16 : COPY requirements.txt /

 ---> Using cache

 ---> 6f85a9d3df8f

Step 7/16 : RUN mkdir -p /etc/dsmr_logs

 ---> Using cache

 ---> 4ffad460c556

Step 8/16 : RUN pip install --no-cache-dir -r requirements.txt

 ---> Running in 30c666d29348

Fatal Python error: pyinit_main: can't initialize time
Python runtime state: core initialized
PermissionError: [Errno 1] Operation not permitted

Current thread 0x76fc9390 (most recent call first):
<no Python frame>

Removing intermediate container 30c666d29348`

Can you help me how to fix this?

**Comment by sanderdw** [comment]
Strange, never seen this issue before. Can you tell me a little more about your set-up? And can you check if you can install the reader?

**Comment by ymestechwey** [comment]
The reader works, I have Hassio installed on a RPI. Running Home Assistant 2021.3.4

**Comment by sanderdw** [comment]
Which RPI version specifically? Do you run the latest Home Assistant OS 5.12 and supervisor-2021.03.6?

**Comment by ymestechwey** [comment]
## System Health

version | core-2021.3.4
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.51-v7+
arch | armv7l
timezone | Europe/Amsterdam

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | Raspbian GNU/Linux 10 (buster)
-- | --
update_channel | stable
supervisor_version | supervisor-2021.03.6
docker_version | 19.03.13
disk_total | 54.8 GB
disk_used | 25.8 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.2.0), MariaDB (2.2.2), Portainer (1.4.0), Terminal & SSH (9.1.0), Mosquitto broker (5.1.1), DSMR Reader (0.3.1)

</details>

**Comment by sanderdw** [comment]
Think this has to do with your type of installation. Can you switch over to Home Assistant OS?

If you can't maybe check https://github.com/home-assistant/supervised-installer#troubleshooting or try to fully remove and install the addon again.
