### ISSUE TITLE
Support for DATALOGGER_SLEEP

### ISSUE THREAD

**Issue by geertsmichael** [sanderdw/hassio-addons#15]
Could you add DATALOGGER_SLEEP?
This add-on posts a telegram every 0.5 seconds and is way too much data for me.
I also can't block this on the DSMR Reader instance as every telegram send is processed.
This is also causing way too much MQTT events for me.

Could you looking supporting the default DATALOGGER_SLEEP config?

Thanks in advance.

**Comment by sanderdw** [comment]
Can you test this with the new DSMR-reader 0.3.1 release?

**Comment by geertsmichael** [comment]
Sorry, I missed an important part, I am using https://github.com/sanderdw/hassio-addons/tree/master/dsmr_datalogger
And the 0.3.1 release is only available for the receiver end of DSMR.
So it would be fantastic if you could also add this to the datalogger.

I tried this change, and it has no effect, as I assume it only applies to the instance that is reading the DSMR data (and not the receiver).

**Comment by sanderdw** [comment]
Now available in the datalogger as well.

**Comment by geertsmichael** [comment]
Great. This works like a charm. Thanks 🙏
