### ISSUE TITLE
backup restore

### ISSUE THREAD

**Issue by cargnellogiacomo** [sanderdw/hassio-addons#18]
Hi,

I was using DSMR (both datalogger and application) installed directly on Raspbian and I decided to move to HassOS where I installed this addon for Hassio.
I have a DSMR backup from my previous Raspbian installation and I tried to restore it within this addon without success.
Any suggestions or guidance for it?
Thank you and regards

Giacomo

**Comment by sanderdw** [comment]
Hi Giacomo, sorry for responding a bit late. I would suggest to go trough this topic https://community.home-assistant.io/t/dsmr-reader-add-on-for-home-assistant/279087/ to find some instructions. You can also post your question there.

**Comment by cargnellogiacomo** [comment]
I was indeed able to restore my old backup following this [post](https://community.home-assistant.io/t/dsmr-reader-add-on-for-home-assistant/279087/8).
Very helpful. thx a lot
