### ISSUE TITLE
Invalid Add-on repository with HA 2021.6 Beta?

### ISSUE THREAD

**Issue by Bascht74** [sanderdw/hassio-addons#19]
I get the following error für HA 2021.6. 
Could you take a look at it if it is in 2021.6 or your Repro?

Thx, 

Seb

![image](https://user-images.githubusercontent.com/66269310/120101548-cf04c580-c146-11eb-96ad-d7e4c77bba80.png)

The URL is: https://github.com/sanderdw/hassio-addons

## System Health

version | core-2021.6.0b1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 5.9.16
arch | aarch64
timezone | Europe/Berlin

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.12.4
Stage | running
Available Repositories | 900
Installed Repositories | 48

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 4. Juni 2021, 2:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.0.rc3
-- | --
update_channel | beta
supervisor_version | supervisor-2021.05.3
docker_version | 20.10.6
disk_total | 113.9 GB
disk_used | 35.4 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | Node-RED (9.1.3), AppDaemon 4 (0.6.1), Mosquitto broker (6.0.1), Log Viewer (0.11.0), TasmoAdmin (0.15.0), TasmoBackup (1.04.13), Visual Studio Code (3.4.1), Frigate NVR (1.13), JupyterLab (0.5.0), Home Assistant Google Drive Backup (0.104.3), WireGuard (0.5.1), Duck DNS (1.12.5), ESPHome (1.18.0), SSH & Web Terminal (8.2.3), MariaDB (2.3.0), Portainer (1.5.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 20
views | 9
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by Bascht74** [comment]
No Response :-(
I used another way...

**Comment by pertakman** [comment]
I can't seem to get this to work either. What other way did you use?

**Comment by Bascht74** [comment]
https://www.home-assistant.io/integrations/dsmr_reader/
