### ISSUE TITLE
Update interval sensors 

### ISSUE THREAD

**Issue by Ivar247** [sanderdw/hassio-addons#20]
Hi All,

## Problem definition
After integrating DSMR Reader Docker in The supervisor of Home Assistant  all sensor integrations in HA is updating every 5 seconds. After a couple of days the update interval changes resulting in wrong calculations combining different sensor data.

After 1) Rebuilding DSMR Reader and 2) Restarting TimescaleDB the sensor update every 5 seconds again.
You can this happening in the attached screenshot. (please don't mind the units of each variable they are not labelled correctly)

How can i make sure the sensor update interval stays within 5 seconds ? With previous builds i didn't have this issue of intervals changing.

Thanks a lot for your support.

Best regards,
Ivar Engel

-->
## Setup/Architecture information
ODROID-N2+
-->

## Version of the Docker image
-DSMR Reader Current version: 0.5.0
-TimescaleDB Current version: 1.1.6
-Running in Supervisor in Home Assistant Versioncore-2021.8.8

## Debug log

![Screenshot 2021-09-08 131834](https://user-images.githubusercontent.com/79230092/132500289-6ebcacb4-4766-4ec5-b2f2-b5a0a61d1fd8.png)

Add your logs here.

```

**Comment by sanderdw** [comment]
Hi @Ivar247, just wanted to let you now that i missed some Github notifications including this one. Do you still have problems with the latest version?

**Comment by Ivar247** [comment]
Hi Sander ,

It actually started acting up last night again. Let me update everything
and see how it goes.

Thanks for reaching out, I'll let you know how it goes.
Best regards ,
Ivar Engel

**Comment by sanderdw** [comment]
I Ivar,

I assume you problem is fixed, so i'm closing this issue now. Feel free to open it again when you still have issues on the new 0.7.3 release.

**Comment by Ivar247** [comment]
Hi Sander,

Yes sorry , after the update it didn't occur anymore !

Cheers again,

Best regards,
Ivar
