### ISSUE TITLE
Feature request: add verbose logging option

### ISSUE THREAD

**Issue by balk77** [sanderdw/hassio-addons#22]
Hi, thanks for maintaining this addon! 

Today I ran into a problem and wanted to increase verbosity of the logs. I had to install the xirixiz docker image to be able to do that. Could you please make this a configurable option for the addon? The code seems to be already there:

https://github.com/sanderdw/hassio-addons/blob/6ec213f45673dfa4de4e55cdfc1aa459247a4a84/dsmr_reader/run.sh#L151-L153

**Comment by sanderdw** [comment]
Hi @balk77, just wanted to let you now that i missed some Github notifications but i will add this feature for sure. Hopefully somewhere this week.

**Comment by sanderdw** [comment]
Hi @balk77, just released 0.7.3 which has some debug options.
