### ISSUE TITLE
Reverse proxy support

### ISSUE THREAD

**Issue by rickk88** [sanderdw/hassio-addons#24]
Would it be possible to support the environmental variables for reverse proxy support?

https://dsmr-reader.readthedocs.io/en/v4/reference/env-settings.html#django-use-x-forwarded-host
https://dsmr-reader.readthedocs.io/en/v4/reference/env-settings.html#django-static-url

https://github.com/dsmrreader/dsmr-reader/issues/1080

**Comment by sanderdw** [comment]
Hi @rickk88, just wanted to let you now that i missed some Github notifications including this one. I tried this a while back but ran into different problems. I can look into it again if you want me too, what's your goal?

**Comment by rickk88** [comment]
Hi Sander, I want to put the unencrypted port 7777 behind a reverse proxy that uses SSL, as non-HTTPS connections might be flagged in the future by the browsers and to not pass passwords over the network in plain text :)

**Comment by sanderdw** [comment]
But that already works right? So you have internet <-ssl-> reverseproxy <-non-ssl-> dsmrreader-ip:7777? Or do you refer to Ingress support (https://developers.home-assistant.io/docs/add-ons/presentation#ingress)

**Comment by rickk88** [comment]
No, I want to publish https://proxy.domain.ext/dsmr -> dsmrreader-ip:7777
But because of the /dsmr I get error "Not Found. The requested resource was not found on this server"

**Comment by sanderdw** [comment]
Don't know how to properly configure this, it should be the right combination of:
https://github.com/sanderdw/hassio-addons/blob/ingress_test/dsmr_reader/nginx/dsmr-webinterface
https://github.com/sanderdw/hassio-addons/blob/ingress_test/dsmr_reader/rootfs/etc/services.d/nginx/run#L39-L43

I think we need to find someone who can help.

**Comment by rickk88** [comment]
Not very knowledgeable in all of this, but I think you're almost there :)

In https://github.com/sanderdw/hassio-addons/blob/master/dsmr_reader/run.sh

Would it be possible to show the options for these settings in the package:
DJANGO_STATIC_URL
DJANGO_FORCE_SCRIPT_NAME
DJANGO_USE_X_FORWARDED_HOST

Each of these should only be set as an environmental variable when the value isn't empty, or otherwise have a default:
DJANGO_STATIC_URL="None"
DJANGO_FORCE_SCRIPT_NAME="None"
DJANGO_USE_X_FORWARDED_HOST="False"

For my environment it would be:
DJANGO_STATIC_URL="/dsmr/"
DJANGO_FORCE_SCRIPT_NAME="/dsmrreader"
DJANGO_USE_X_FORWARDED_HOST="True"

At least that's what I think..

**Comment by sanderdw** [comment]
Hi @rickk88 , can you try the new Ingress support? See https://github.com/sanderdw/hassio-addons/issues/42#issuecomment-1121577693

**Comment by rickk88** [comment]
Hi Sander, Ingress works like a charm! Will you still work on allowing manual configuration of some environmental variables for those not using Ingress? (That way we can choose to use Ingress or something like Nginx Proxy Manager as a reverse proxy)

**Comment by sanderdw** [comment]
Should not be that hard, in order for that to work you only want to be able to configure DJANGO_STATIC_URL and DJANGO_FORCE_SCRIPT_NAME right?

**Comment by rickk88** [comment]
I think so yeah.

**Comment by sanderdw** [comment]
I have a test version ready in the develop branch, can you test it?

1. Uninstall current addon
2. Go to https://github.com/sanderdw/hassio-addons/tree/develop - find Code button  -> Download ZIP
3. From that zip file, only copy the 'dsmr_reader' folder and place it in your \\hassioip\addons\ directory (you can use the Samba share addon). 
4. In Home Assistant -> Add-on store -> In the top right press 'Check for updates' and DSMR Reader should appear right on the top under 'Local add-ons'.
5. Install and configure the addon, choose the 'Custom' option under webserver and make sure you fill the DJANGO_FORCE_SCRIPT_NAME and DJANGO_STATIC_URL options.

**Comment by rickk88** [comment]
Hi Sander, I haven't figured out a working configuration with my proxy manager, maybe it's missing "DJANGO_USE_X_FORWARDED_HOST" ?

**Comment by sanderdw** [comment]
What proxy manager are you using and how do you want to set it up?

DJANGO_USE_X_FORWARDED_HOST is always set to True

**Comment by rickk88** [comment]
Trying to use Nginx Proxy Manager (HA Addon) forwarding https://ha.domain.ext/dsmr to http://ha-ip:7777

**Comment by sanderdw** [comment]
It should work, i created a test setup myself:

<img width="919" alt="image" src="https://user-images.githubusercontent.com/19476345/168677997-e6b0a0c1-da6c-4e4d-acdd-0a99f3899180.png">

<img width="661" alt="image" src="https://user-images.githubusercontent.com/19476345/168678233-31996d61-a5bc-4bc5-af99-346493e3c079.png">

<img width="731" alt="image" src="https://user-images.githubusercontent.com/19476345/168678286-c0921e70-6843-4f20-b92f-8fd209bbdc59.png">

<img width="743" alt="image" src="https://user-images.githubusercontent.com/19476345/168678392-512adb01-d274-4790-aabb-4cfdb75d2dc7.png">

**Comment by rickk88** [comment]
Hi Sander, that helped me in the right direction.
I configured:
 DJANGO_FORCE_SCRIPT_NAME    as    /dsmr
 DJANGO_STATIC_URL    as    /dsmr/static/

And the proxy like you provided. Had to restart my proxy manager before it started working, which I might have not done enough or was impatient.
You're the man!

**Comment by sanderdw** [comment]
Released: https://community.home-assistant.io/t/dsmr-reader-add-on-for-home-assistant/279087/268?u=sanderdw
