### ISSUE TITLE
Cannot Install DSMR addon in Home Assistant latest version

### ISSUE THREAD

**Issue by hscholing** [sanderdw/hassio-addons#25]
When trying to install the DSMR HA addon I receive the following error:

manifest for xirixiz/dsmr-reader-docker:latest-2021.10.02-amd64 not found: manifest unknown: manifest unknown

I cannot install the addon

**Comment by Rocker20** [comment]
@sanderdw can you update this? I think it should be xirixiz/dsmr-reader-docker:latest so is gold me

**Comment by sanderdw** [comment]
Yes, working on it now

**Comment by Rocker20** [comment]
No problem at all! I can wait 😉

**Comment by sanderdw** [comment]
Hi @hscholing and @Rocker20 , i provided a quick fix which is now in the new 0.7.1 update. Please let me know if it's working again.

**Comment by Rocker20** [comment]
Installation looks oké, but i forgot the postgress password so now it won't work yet but i will be back when to you when i'm on my laptop again

**Comment by Rocker20** [comment]
Hello @sanderdw 

had a few usb errors on boot so it seems that the datalogger configuration is not picked up on initial boot. After that everything seems to work properly, but unfortunately it doesn't solve the integration problems with home assistant so thanks for the effort, but I think I'm forced to do a system restore from Sunday. Hopefully you can help the others with their usb notifications in the other issue reports. Thanks again for the effort on such short notice! I also had the message for a while last week but of course I don't know how busy you are so didn't want to be annoying right away

**Comment by sanderdw** [comment]
Just published 0.7.2, let me know if it works.
