### ISSUE TITLE
High CPU load (>90%)

### ISSUE THREAD

**Issue by hugodejong** [sanderdw/hassio-addons#28]
Since a recent restart of the add-on, I've been seeing a CPU load that's way too high to be normal:

![image](https://user-images.githubusercontent.com/53058265/149838388-5c4baf00-b5fc-4cfb-a381-23ec7026cdfd.png)

Data is coming into HA through MQTT and the web interface is available, so everything seems to work. The add-on log shows a lot of this:

`127.0.0.1 - - [17/Jan/2022:22:22:14 +0100] "GET /about HTTP/1.1" 200 14772 "-" "curl/7.79.1" "-"

127.0.0.1 - - [17/Jan/2022:22:22:19 +0100] "GET /about HTTP/1.1" 200 14772 "-" "curl/7.79.1" "-"

127.0.0.1 - - [17/Jan/2022:22:22:24 +0100] "GET /about HTTP/1.1" 200 14772 "-" "curl/7.79.1" "-"

127.0.0.1 - - [17/Jan/2022:22:22:30 +0100] "GET /about HTTP/1.1" 200 14772 "-" "curl/7.79.1" "-"

127.0.0.1 - - [17/Jan/2022:22:22:35 +0100] "GET /about HTTP/1.1" 200 14772 "-" "curl/7.79.1" "-"

127.0.0.1 - - [17/Jan/2022:22:22:40 +0100] "GET /about HTTP/1.1" 200 14772 "-" "curl/7.79.1" "-"

127.0.0.1 - - [17/Jan/2022:22:22:46 +0100] "GET /about HTTP/1.1" 200 14772 "-" "curl/7.79.1" "-"

127.0.0.1 - - [17/Jan/2022:22:22:51 +0100] "GET /about HTTP/1.1" 200 14772 "-" "curl/7.79.1" "-"

127.0.0.1 - - [17/Jan/2022:22:22:56 +0100] "GET /about HTTP/1.1" 200 14772 "-" "curl/7.79.1" "-"

127.0.0.1 - - [17/Jan/2022:22:23:01 +0100] "GET /about HTTP/1.1" 200 14772 "-" "curl/7.79.1" "-"

127.0.0.1 - - [17/Jan/2022:22:23:07 +0100] "GET /about HTTP/1.1" 200 14772 "-" "curl/7.79.1" "-"

127.0.0.1 - - [17/Jan/2022:22:23:12 +0100] "GET /about HTTP/1.1" 200 14772 "-" "curl/7.79.1" "-"

127.0.0.1 - - [17/Jan/2022:22:23:17 +0100] "GET /about HTTP/1.1" 200 14772 "-" "curl/7.79.1" "-"

127.0.0.1 - - [17/Jan/2022:22:23:22 +0100] "GET /about HTTP/1.1" 200 14772 "-" "curl/7.79.1" "-"

127.0.0.1 - - [17/Jan/2022:22:23:28 +0100] "GET /about HTTP/1.1" 200 14772 "-" "curl/7.79.1" "-"

127.0.0.1 - - [17/Jan/2022:22:23:33 +0100] "GET /about HTTP/1.1" 200 14772 "-" "curl/7.79.1" "-"`

Currently running v0.7.3. 

I've tried:

- Reverting the add-on to a previous version (0.7.2 I think), same problem
- Rebooting the VM in which HA and the add-on run
- Rebooting the host machine

**Comment by Sholofly** [comment]
Yeah, definately too high:
![image](https://user-images.githubusercontent.com/901632/149839725-415b3cee-5937-42af-a7e6-a11ca65bca82.png)

**Comment by ecoenjaerts** [comment]
Also see a sudden rise in CPU usage. Add on log contains multiple Errors. I am not an expert at all, but maybe this helps.

127.0.0.1 - - [18/Jan/2022:08:10:59 +0100] "GET /about HTTP/1.1" 200 14772 "-" "curl/7.79.1" "-"
127.0.0.1 - - [18/Jan/2022:08:11:04 +0100] "GET /about HTTP/1.1" 200 14772 "-" "curl/7.79.1" "-"
127.0.0.1 - - [18/Jan/2022:08:11:09 +0100] "GET /about HTTP/1.1" 200 14772 "-" "curl/7.79.1" "-"
127.0.0.1 - - [18/Jan/2022:08:11:14 +0100] "GET /about HTTP/1.1" 200 14772 "-" "curl/7.79.1" "-"
127.0.0.1 - - [18/Jan/2022:08:11:20 +0100] "GET /about HTTP/1.1" 200 14772 "-" "curl/7.79.1" "-"
127.0.0.1 - - [18/Jan/2022:08:11:25 +0100] "GET /about HTTP/1.1" 200 14772 "-" "curl/7.79.1" "-"
2022-01-18 08:11:27,547 ERROR    schedule     execute_scheduled_processes      37 | (PermissionError) dsmr_backup.services.backup.run errored: [Errno 13] Permission denied: '/backup/dsmrreader/dsmrreader-postgresql-backup-Tuesday.sql'
127.0.0.1 - - [18/Jan/2022:08:11:30 +0100] "GET /about HTTP/1.1" 200 14772 "-" "curl/7.79.1" "-"
127.0.0.1 - - [18/Jan/2022:08:11:36 +0100] "GET /about HTTP/1.1" 200 14772 "-" "curl/7.79.1" "-"
127.0.0.1 - - [18/Jan/2022:08:11:42 +0100] "GET /about HTTP/1.1" 200 14772 "-" "curl/7.79.1" "-"
127.0.0.1 - - [18/Jan/2022:08:11:47 +0100] "GET /about HTTP/1.1" 200 14772 "-" "curl/7.79.1" "-"
127.0.0.1 - - [18/Jan/2022:08:11:52 +0100] "GET /about HTTP/1.1" 200 14772 "-" "curl/7.79.1" "-"
127.0.0.1 - - [18/Jan/2022:08:11:57 +0100] "GET /about HTTP/1.1" 200 14772 "-" "curl/7.79.1" "-"
2022-01-18 08:11:58,101 ERROR    schedule     execute_scheduled_processes      37 | (PermissionError) dsmr_backup.services.backup.run errored: [Errno 13] Permission denied: '/backup/dsmrreader/dsmrreader-postgresql-backup-Tuesday.sql'
127.0.0.1 - - [18/Jan/2022:08:12:03 +0100] "GET /about HTTP/1.1" 200 14772 "-" "curl/7.79.1" "-"
127.0.0.1 - - [18/Jan/2022:08:12:08 +0100] "GET /about HTTP/1.1" 200 14772 "-" "curl/7.79.1" "-"
127.0.0.1 - - [18/Jan/2022:08:12:13 +0100] "GET /about HTTP/1.1" 200 14772 "-" "curl/7.79.1" "-"
127.0.0.1 - - [18/Jan/2022:08:12:18 +0100] "GET /about HTTP/1.1" 200 14772 "-" "curl/7.79.1" "-"
127.0.0.1 - - [18/Jan/2022:08:12:24 +0100] "GET /about HTTP/1.1" 200 14772 "-" "curl/7.79.1" "-"
2022-01-18 08:12:28,979 ERROR    schedule     execute_scheduled_processes      37 | (PermissionError) dsmr_backup.services.backup.run errored: [Errno 13] Permission denied: '/backup/dsmrreader/dsmrreader-postgresql-backup-Tuesday.sql'

**Comment by hugodejong** [comment]
Also seeing these PermissionErrors now.

**Comment by sanderdw** [comment]
Not tested well enough, i see... To fix these errors on the new set-up i need some extra time so in the mean time i published DSMR-reader 0.7.3 which is just the previous working config. Let me know if that fixes it for now.

**Comment by Sholofly** [comment]
0.7.3 was already the latest version, wasn't it? I don't see updates now...

**Comment by sanderdw** [comment]
I need to wake up, yes indeed DSMR-reader 0.7.4 👍

**Comment by Sholofly** [comment]
That looks good!

![image](https://user-images.githubusercontent.com/901632/149939207-2a724e3d-2422-44ad-b4d6-9557e9932857.png)

**Comment by Alfagek** [comment]
Thanks for the quick “fix” @sanderdw   the new-old version 0.7.4 works again with almost no cpu power again

**Comment by hugodejong** [comment]
My HA has not detected the update yet, will let you know whether it has fixed it. Is there a trick to have HA check for add-on updates? :)

**Comment by hugodejong** [comment]
Works like a dream again. Thank you @sanderdw for the speedy solve!
