### ISSUE TITLE
DSRM Reader 

### ISSUE THREAD

**Issue by alexswart** [sanderdw/hassio-addons#3]
Hello,

is it possible to also make an DSRM Reader dashboard addon?

**Comment by sanderdw** [comment]
Hi Alex,

You mean like not only running only the datalogger as addon but also the application itself?

Yes it could be build but you can also use https://github.com/hassio-addons/addon-portainer this addon to install it yourself (also working on the raspberry):

1. Install Portainer
2. With Portainer, install Postgres (https://hub.docker.com/_/postgres)
3. With Portainer, install dsmr-reader by xirixiz (https://hub.docker.com/r/xirixiz/dsmr-reader-docker)

Let me know if this works for you.

**Comment by sanderdw** [comment]
@alexswart i released the full DSMR Reader addon, would love your feedback: https://github.com/sanderdw/hassio-addons/tree/master/dsmr_reader
