### ISSUE TITLE
Add-on crashes when configured to read data over ipv4

### ISSUE THREAD

**Issue by hugodejong** [sanderdw/hassio-addons#31]
Recently purchased a wifi smart meter gateway that distributes telegrams over telnet. When I configure the add-on for that, it reports an error and crashes:

![image](https://user-images.githubusercontent.com/53058265/150942187-4bdb8309-7cec-47b0-82df-92b05bcce0bb.png)

Configured like this:

![image](https://user-images.githubusercontent.com/53058265/150942276-7442b102-ce74-4718-b3c7-ce1515786b62.png)

Telnetting from another machine in the network shows that the gateway is available and reporting telegrams:

![image](https://user-images.githubusercontent.com/53058265/150942498-92294e38-8006-4988-9cf7-b9fe3c5d5314.png)

Temporarily using the HA DSMR integration which also connects through telnet, so I suspect something is going wrong with the add-on.

**Comment by sanderdw** [comment]
Hi Hugo, maybe you can test the new beta version? Here are the steps: https://community.home-assistant.io/t/dsmr-reader-add-on-for-home-assistant/279087/180?u=sanderdw

**Comment by hugodejong** [comment]
That seems to work fine, thank you @sanderdw! I'll keep running the beta for now, along the DSMR integration of HA. Is there a specific channel for beta feedback I can use in case I have any?

**Comment by sanderdw** [comment]
Great, just released the final so you can reinstall it from there. Feedback can be left here: https://community.home-assistant.io/search?q=%40sanderdw%20%23home-assistant-os
