### ISSUE TITLE
Advies (geen ISSUE!) t.b.v. DSMR Reader & backup/restore

### ISSUE THREAD

**Issue by niekniek89** [sanderdw/hassio-addons#35]
Hallo,

Ik heb even een "open" vraag m.b.t. het gebruik van DSMR Reader.
Deze gebruik ik nu naar volle tevredenheid op een losse Linux VM (waarop docker aanwezig is).
De Linux VM draait binnen ESXI (waar ook een losse VM draait met HassOS).

Echter draai ik deze Linux VM machine bijna alleen, t.b.v. DSMR Reader.
Nu zag ik deze Addon, en is wellicht een serieuze optie om "de boel" te migreren naar deze Addon.

Zijn er al eerder gebruikers geweest welke hetzelfde gedacht/gedaan hebben?
Is het aan te raden om te "migreren" vanaf mijn Linux VM naar deze Addon, en gaat dat allemaal wel qua history/database?

Dit zou voor mij betekenen dat ik weer qua onderhoud 1 VM minder heb :)!
Zie graag uit naar jullie mening 👍.

**Comment by niekniek89** [comment]
Bedankt voor je antwoord.
Ik draai nu inderdaad DSMR binnen docker, op 20.04LTS.
Dan laat ik het maar voor wat het is, draait prima, was ook maar een vraag!

**Comment by sanderdw** [comment]
Wat wil je precies migreren? Wil je de TimescaleDB addon gaan gebruiken voor de Postgres data?

**Comment by niekniek89** [comment]
Ik wil inderdaad de database (mijn huidige met +4 jaar aan data) migreren naar bijv. TimescaleDB.
Wil dus, als dat mogelijk is, alle history meenemen naar jou addon.

**Comment by niekniek89** [comment]
gaat verder via:

https://github.com/sanderdw/hassio-addons/issues/57
