### ISSUE TITLE
Background processing broken?

### ISSUE THREAD

**Issue by dennisbrouwer91** [sanderdw/hassio-addons#37]
Hi,

After upgrading to the 5.1 version my DSMR Reader instance isn't processing the received data anymore.
See screenshot
<img width="907" alt="Schermafbeelding 2022-04-04 om 11 57 48" src="https://user-images.githubusercontent.com/17491836/161520888-d19dabb1-5ba9-4dc1-93fc-13414f6a8f80.png">
.

Any known issue?

**Comment by sanderdw** [comment]
You need to post the log of the addon. Also explain how your setup looks like. The are also other issues like https://community.home-assistant.io/t/dsmr-reader-add-on-for-home-assistant/279087/208?u=sanderdw possible.

**Comment by dennisbrouwer91** [comment]
Yes, agreed. I think this part of the log is interesting : 
`2022-04-04 12:01:53,521 ERROR    schedule     execute_scheduled_processes      37 | (IntegrityError) dsmr_consumption.services.run errored: null value in column "delivered_1" violates not-null constraint
DETAIL:  Failing row contains (437786, 2022-04-01 06:58:00+00, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null).`

TimeScaleDB Has been rolled back indeed because of it breaking after the upgrade.
Setup is pretty simple : Smart meter -> P1 to USB cable directly to my Intel NUC which is running HassIO in Supervised mode. Worked until the upgrade!

**Comment by sanderdw** [comment]
Maybe have a look here as it's not related to the addon but to the software itself? https://github.com/dsmrreader/dsmr-reader/issues/1288
