### ISSUE TITLE
dsmr-reader is not a valid add-on repository

### ISSUE THREAD

**Issue by spijkey87** [sanderdw/hassio-addons#4]
Hello,

I tried to add your addon to supervisor but it doesn't install or rather add your repo to my system.

Hostname homeassistant
Operating System HassOS 4.17
Deployment production 

Supervisor
Version 2020.12.6
Channel stable 

The log says:
ERROR (MainThread) [supervisor.store] https://github.com/dsmrreader/dsmr-reader is not a valid add-on repository

**Comment by sanderdw** [comment]
Hi,

You are using the dsmr-reader git repo (https://github.com/dsmrreader/dsmr-reader) and not my addon-repo (https://github.com/sanderdw/hassio-addons).

**Comment by spijkey87** [comment]
I'm an idiot. You're the best tnks
