### ISSUE TITLE
Datalogger addon update to 1.1.0 fails

### ISSUE THREAD

**Issue by Melantrix** [sanderdw/hassio-addons#41]
The update (from 1.0.3) to 1.1.0 fails for me with the following message:

bin/ash -o pipefail -c pip install --no-cache-dir -r requirements.txt' returned a non-zero code: 127

Shouldn't it be bin/bash in stead of bin/ash?

**Comment by sanderdw** [comment]
Yes, if that happens you need to uninstall and reinstall/reconfigure the addon. As the addon is now pre build it seems that HA can't seamlessly update it. Let me know if it works.

**Comment by Melantrix** [comment]
Yea looks like that fixed it. Thanks!
