### ISSUE TITLE
Dashboard in home assistant sidebar

### ISSUE THREAD

**Issue by tdn131** [sanderdw/hassio-addons#42]
I would like to see the DSMR statistics dashboard from within the home assistant app. Would it be possible to integrate DSMR in the sidebar of Home Assistant? 

I believe it can be achieved using Ingress (like AdGuard Home and ESPHome). [https://developers.home-assistant.io/docs/add-ons/presentation/#ingress](url)

I don't know how difficult it is to implement. I would really appreciate it. Thanks!

**Comment by sanderdw** [comment]
https://github.com/sanderdw/hassio-addons/issues/24

Yes it was already mentioned a while ago. I can put some time in again soon and see how it goes. Should be duable but just need to know how to put it all together.

**Comment by tdn131** [comment]
Hi Sander. Thanks for your quick work. I can confirm this works. I am very happy with this feature!

I thought you meant by enable in config: Show in sidebar, but it's also Enable_Ingress in configuration. Do I understand correctly that 7777 is not to be used anymore when Ingress is enabled? It still works, but it looks like there is no stylesheet (CSS) present. When I only enabled Show in sidebar (without Enable_Ingress) it looked the same:
![afbeelding](https://user-images.githubusercontent.com/32997056/167547143-e6c6d3ba-fe3b-4903-8fdf-cb7466bbe028.png)

I did uninstall though and I noticed DJANGO_DATABASE_HOST default to 77b2833f-timescaledb, while the latest TimescaleDB 2.01 is 1d11d3ee_timescaledb. You could also change that ;).

**Comment by sanderdw** [comment]
> Hi Sander. Thanks for your quick work. I can confirm this works. I am very happy with this feature!
> 
> I thought you meant by enable in config: Show in sidebar, but it's also Enable_Ingress in configuration. Do I understand correctly that 7777 is not to be used anymore when Ingress is enabled? 
Correct, i clarified some things here: https://community.home-assistant.io/t/dsmr-reader-add-on-for-home-assistant/279087/244?u=sanderdw
> 
> I did uninstall though and I noticed DJANGO_DATABASE_HOST default to 77b2833f-timescaledb, while the latest TimescaleDB 2.01 is 1d11d3ee_timescaledb. You could also change that ;).

Hmm it's still the same for me? Are u sure?
