### ISSUE TITLE
SOLVED: Since last update DSRM Reader (Current version: 1.2.0) it won't start

### ISSUE THREAD

**Issue by poudenes** [sanderdw/hassio-addons#45]
After I updated DSRM Reader to 1.2.0 it won't start:

Home Assistant Core 2022.5.3
Home Assistant Supervisor 2022.05.0
Home Assistant OS 7.6
Kernel version 5.10.103-v8
Agent version 1.2.1

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-set-hassio-vars: executing... 
Home Assistant DSMR Reader Add-on - Release: 1.2.0
Home Assistant DSMR Reader Add-on - This addon is the latest version
Home Assistant DSMR Reader Add-on - Configuring addon settings
printf: usage: printf [-v var] format [arguments]
[cont-init.d] 01-set-hassio-vars: exited 2.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by sanderdw** [comment]
Hi, which hardware are you running on?

**Comment by DavyRoswinkel** [comment]
With my it only worked after uninstalling and reinstalling.

Works great now

**Comment by sanderdw** [comment]
@DavyRoswinkel, did you had the same 'printf' error at first? Can you also tell me if you are using Ingress or the old '7777' port now?

**Comment by poudenes** [comment]
> Hi, which hardware are you running on?

Running RPi4 with a serial connected hardware to read my stats

Uninstall and reinstall didn't work for me... I will try it again and don't replace the old yaml information. just add the serial link and database information.

**Comment by sanderdw** [comment]
> > Hi, which hardware are you running on?
> 
> Running RPi4 with a serial connected hardware to read my stats
> 
> Uninstall and reinstall didn't work for me... I will try it again and don't replace the old yaml information. just add the serial link and database information.

Strange, i also tested it on a RPi4 with the serial cable attached to it (so same set-up). I have to admit upgrading is not seamless (see known issues here https://www.home-assistant.io/blog/2019/04/15/hassio-ingress/) so it would be best to manually uninstall and reinstall again and reconfiguring the addon (should not be a lot of work).

**Comment by poudenes** [comment]
Removed add-on. Wait some minutes.. Reinstalled add-on. Start it. Running well. Changed dB information. start again running wel again. Everything is back on track!

**Comment by sanderdw** [comment]
> Removed add-on. Wait some minutes.. Reinstalled add-on. Start it. Running well. Changed dB information. start again running wel again. Everything is back on track!
> 
> The difference between the first update and remove and reinstall add-on:
> 
> after first update:
> 
> ```
> DSMRREADER_REMOTE_DATALOGGER_SERIAL_BAUDRATE: ''
> DSMRREADER_REMOTE_DATALOGGER_NETWORK_HOST: ''
> DSMRREADER_REMOTE_DATALOGGER_NETWORK_PORT: ''
> ```
> 
> after remove and reinstall:
> 
> ```
> DSMRREADER_REMOTE_DATALOGGER_SERIAL_BAUDRATE: '115200'
> DSMRREADER_REMOTE_DATALOGGER_NETWORK_HOST: x.x.x.x
> DSMRREADER_REMOTE_DATALOGGER_NETWORK_PORT: x
> ```
> 
> Can this create the problem that the host and port went empty.

Yes could be it, tried to make some fields optional and it seems that can cause some issue's. Reverted it for now which should fix some upgrading issues.
