### ISSUE TITLE
Network socket

### ISSUE THREAD

**Issue by Toolhead** [sanderdw/hassio-addons#5]
I have DSRM Reader running on a seperate Pi through network socket.
I want to ditch that and install the add-on in HA, but can I use web socket in the add-on?

**Comment by sanderdw** [comment]
Could you explain your situation a bit more? It's not clear for me what you need on my end. Happy to help you.

**Comment by Toolhead** [comment]
I have 2 Pi's, 1 is running Home Assistant, the other one is running DSMR-Reader.
The source for the data is an ESP device which sends it over the network.
In DSMR-Reader you can choose between USB and network socket.
I want to get rid of the Pi running DSMR-Reader and install your add-on in the Pi running Home Assistant.
There I do not see ( in the config file ) the option to have data coming in from the network socket, only serial option is there.

Well, I just went ahead with the default settings and the option for websocket could be chosen from the configuration, so it's up and running now, you can close this.

**Comment by sanderdw** [comment]
Can be configured correctly.
