### ISSUE TITLE
External datalogger /  API not working after upgrade to 1.2.1

### ISSUE THREAD

**Issue by 2xdehelft** [sanderdw/hassio-addons#50]
After upgrading from 1.2.0 to 1.2.1 there is no data received from my remote datalogger. Tried resetting the config but no change. Restoring to 1.2.0 fixed it for now.

With 1.2.0 I can connect to port 7777, with the new version 1.2.1 this port seems to be closed.

**Comment by sanderdw** [comment]
Good point, didn't really think of that but you just need to set this in the configuration:

<img width="836" alt="image" src="https://user-images.githubusercontent.com/19476345/170234312-f35d7bcd-f3b6-47df-8dcb-b87a2003977e.png">

So tick "Show disabled ports" and fill in the port you need, ex 7777. 

Let me know if this works.

Security wise it's set up correctly (so closed as possible) but i can imagine it confuses a little bit.

**Comment by 2xdehelft** [comment]
Yes its working now, Ingress & API access for remote datalogger both working.

Thanks for the fast reply!
