### ISSUE TITLE
No pictogram in sidebar inside Home Assistant.

### ISSUE THREAD

**Issue by huizebruin** [sanderdw/hassio-addons#53]
![image](https://user-images.githubusercontent.com/62996429/173181944-01a3dda9-e400-47c8-abd8-1522258d12fe.png)

A couple of updates a go the icon for the sidebar disappear en has now been a simple icon.
where there was the logo of dsrm reader  is is now a simple icon

i'm using : 
DSMR Reader
Current version: 1.3.0

**Comment by sanderdw** [comment]
Fixed in 1.3.1, after updating toggle the "Show in sidebar" off and on again.
