### ISSUE TITLE
ERROR    schedule     execute_scheduled_processes      40 | (IntegrityError) 

### ISSUE THREAD

**Issue by poudenes** [sanderdw/hassio-addons#54]
Hi All,

Moved my dB to my NAS. Restored a backup created inside DSMR. 
All my old information is visible in the UI. But no new information will add in the dB. 

I see this error:

```
2022-06-13 12:08:42,067 ERROR    schedule     execute_scheduled_processes      40 | (IntegrityError) dsmr_consumption.services.run errored: null value in column "delivered_1" of relation "dsmr_consumption_electricityconsumption" violates not-null constraint
DETAIL:  Failing row contains (1102161, 2022-06-13 04:00:00+02, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null).
```

What can I do?

I followed this how to:
https://dsmr-reader.readthedocs.io/en/v5/how-to/database/postgresql-restore-backup.html#importing-a-full-backup

**Comment by sanderdw** [comment]
That's a specific application error, maybe you can check the issues here: https://github.com/dsmrreader/dsmr-reader/issues/1619
