### ISSUE TITLE
Postgress/TimescaleDB issue

### ISSUE THREAD

**Issue by cyberjunky** [sanderdw/hassio-addons#63]
I'm running version: 0.7.0 of DSMR reader for years now, very good add-on.

Is there a way to use Hass.io DMSR reader with a 'normal/other' Postgress package? Or another SQL database?

I have issue updating to latest Timescale version, it doesn't start I think because it misses a default homeassistant or admin user with known password.
![image](https://user-images.githubusercontent.com/5447161/188653381-cb74c274-248e-4ebb-becd-6d3e15bc4e5d.png)

Also, is there a way to recover the password for the Postgress/TImescal database so I can make a dump/reload?

**Comment by sanderdw** [comment]
Hi! Thanks for your compliments :).

Yes you can change these settings, just put in the correct external postgres db settings:
<img width="394" alt="image" src="https://user-images.githubusercontent.com/19476345/188964046-9bed8cdd-7077-4171-85d6-45e41e9897a6.png">

Regarding support on the timescale addon, you can go to this thread: https://community.home-assistant.io/t/home-assistant-add-on-postgresql-timescaledb/198176

Let me know if this helps or you need additional help.

**Comment by cyberjunky** [comment]
I fixed the timescale update issue. 
Now onto the dsmr_reader add-on update, but I read that you need to manually enter all settings again, so I need my admin password to see them, before running the update.
I lost the password, trying to reset it I get this error, any pointers?

I logged into homeassistant and run 
```
docker ps |grep dsmr
docker -it {{container_id}} /bin/bash
./manage.py dsmr_superuser
```
Which results in:
![image](https://user-images.githubusercontent.com/5447161/189132759-572d8ca3-0b24-4a20-a06a-66adf057a88b.png)

Where to change/set dsmrdb ip?

**Comment by cyberjunky** [comment]
Arrgg it's just a config item in add-on!

**Comment by cyberjunky** [comment]
When trying to upgrade DSMRreader from 0.7.0 (it's old i know) I get this, is this because it's too old?
Any tips?

![image](https://user-images.githubusercontent.com/5447161/189143799-44ac5c3d-2ad3-4910-9135-88989ef63025.png)

**Comment by cyberjunky** [comment]
Will removing the add-on remove the Postgres dsmr database, or does it stay and will be upgraded when I start the new add-on version? I don't want to loose years of data

**Comment by sanderdw** [comment]
No it will not touch any data :)

**Comment by cyberjunky** [comment]
It worked, sorry for all the questions, those pesky open-source users, I know all about them! ;-)
