### ISSUE TITLE
How to update dsmr-reader? Build in instructions do not work (su dsmr..). 

### ISSUE THREAD

**Issue by prmfeddema** [sanderdw/hassio-addons#66]
Would like to update my dsmr reader (from 5.6 to 5.8). Build in instructions are for another linux install and do not work for home assistant os.
Would you be so kind as to assist/help here on how to get this done.

**Comment by sanderdw** [comment]
I'm not sure if i follow you. You can update the addon in HA itself. Can you tell me more about your setup?
