### ISSUE TITLE
Make Metabase accessible from Home Assistant UI

### ISSUE THREAD

**Issue by CaliLuke** [sanderdw/hassio-addons#68]
Right now I can't access Metabase from outside of my home network, it would be useful to have the UI available in the sidebar like other Add-ons (zigbee2mqtt and pgadmin for example).

**Comment by sanderdw** [comment]
Yes i know, it's not easy to fix this on the addon side. You could use something like https://github.com/hassio-addons/addon-nginx-proxy-manager to achieve the same?
