### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by skank01** [sanderdw/hassio-addons#69]
If i'm correct, current version of dsmr is 5.1
However latest is already 5.9
Any chance to get an update?
I'm asking this cause i would love to have the peak sensors... So i can see capacitytariff in Belgium :)

**Comment by sanderdw** [comment]
Hi @skank01, that's not correct as the addon is on the latest DSMR Reader version for a while. Can you force the update check? Another option is to reboot your HA instance.

**Comment by skank01** [comment]
Hi thats strange, my current version (addon) says its 1.2.0
My dsmr says under support: dsmr reader v 5.1
If i click in check for update under dsmr reader it says theres an update 
If i click check for udpates in HA: it says theres no addon update

**Comment by skank01** [comment]
Any idea? @sanderdw

**Comment by sanderdw** [comment]
I really don't know, as you can see here the addon version should be 1.9.0.

Can you post a screenshot?

**Comment by skank01** [comment]
[url=https://ibb.co/Fbpt2K8][img]https://i.ibb.co/PZk8KN1/shot1.jpg[/img][/url]

[url=https://ibb.co/ZTq7f6H][img]https://i.ibb.co/tCVFHMZ/shot2.jpg[/img][/url]

**Comment by sanderdw** [comment]
Could it be that you using the custom_component variant? So a manual copy?

**Comment by skank01** [comment]
> Could it be that you using the custom_component variant? So a manual copy?

No, i installed it using the addon store.
Before my version now, i had no problems with updating (it autopop automatically)
Now what?
Is there a way to install it without losing settings and history?

**Comment by sanderdw** [comment]
Yes just remember the settings and remove the addon. After that reboot your system and install the addon again. No worries about the data, this is persisted in the database you configured.

**Comment by skank01** [comment]
ok i updated to latest version without loss of data
