### ISSUE TITLE
Update DSMR-reader v5.10.3

### ISSUE THREAD

**Issue by tdn131** [sanderdw/hassio-addons#72]
@sanderdw A new release of DSMR has been published. Xirixiz already released this update. Could you rebase your addon?

Changes are [here](https://dsmr-reader.readthedocs.io/nl/latest/reference/changelog.html).

Thanks!

**Comment by sanderdw** [comment]
Yes I'm aware. For some reason the cicd pipeline is broken. I have to further debug it but unfortunately don't have much time this week.

**Comment by sanderdw** [comment]
It's released!
