### ISSUE TITLE
DSMR-Reader in menu sidebar not available for users, only for administrators

### ISSUE THREAD

**Issue by trinksrichard** [sanderdw/hassio-addons#73]
When I have installed the app and enabled the option to make the option visible in the sidebar, it is not visible to standard users within Home Assistant.
This requires me to make users administrators, which I'd rather not have.

**Comment by sanderdw** [comment]
So apparently i can changes this but that raises the question the other way around. So maybe some administrators don't want to have the app available to end-users. Let me investigate, maybe it's configurable by the ha admin after changing this 👍 .

**Comment by BebeMischa** [comment]
Yes, please, think about this for a while to come with a good solution, where it would be a choice. I definitely dont want my user to access things, they don't understand '. ;-)

**Comment by sanderdw** [comment]
So i checked this and after changing this setting, the user needs to hide it by going to the profile and choosing the edit option "Change the order and hide items from the sidebar". Security wise there is no option to hide is for all non-admins.

**Comment by trinksrichard** [comment]
If I understand you correctly, then I need to make everyone an administrator and then remove the options from the sidebar that they are not allowed to use. That would mean logging into all their devices for that to happen.

In addition, for their 'settings' and 'developer help' remains available what I do not want.
Then I think I have a better option, that the option is available for adminstrators and standard users.
For those who don't want that for their standard users, they can hide the option, as you describe.

Is that an option?

**Comment by BebeMischa** [comment]
> For those who don't want that for their standard users, they can hide the option, as you describe.

No, they can't. For exactly the same reasons. This is a HA shortcoming in global, there is just bad user policy.

Anytime, a user uses a new device to log in, he will be able to see things, he is not supposed to see, if this suggested change will be made.

Definitely a no go with children, older people with pure technical education, bed & breakfast accommodations, rented rooms and so on.
