### ISSUE TITLE
Database importeren naar de addon

### ISSUE THREAD

**Issue by eterpstra** [sanderdw/hassio-addons#76]
Hi,

ik heb DSMR draaien op een ubuntu machine.  Deze machine komt te vervallen.  Hiervoor komt in de plaatst en zuinigere HP Thin client met daarop direct home-assitant geinstalleerd met de DSMR Addon.

Nu wil ik de 3 jarige database die ik heb opgebouwd gaan gebruiken.  Het .sql bestand heb ik inmiddels opgelsagen en kan ik dus (ergens?) naar toe kopieren. De addon + timescale databases zijn aangemaakt met als database namen dsmrreader en homeassistant (default)

Ik zag dat hier al een issue voor was geopend met dezelfde vraag, maar daar werd ik niet echt wijzer van.  Kan ik via de terminal gewoon de database gaan koperen waar de addon deze verwacht? (Zo ja, waar?) 
En welke host moet ik gaan connecten? Het gaat hier om een addon die dus geinstalleerd is van HassOS (Supervised)

**Comment by sanderdw** [comment]
Wat je zou kunnen doen is vanuit de Ubuntu machine (waar je sql dus staat?) de sql file kunnen importen naar je timescale addon db. Je moet dan even de postgres port in die addon naar buiten openzetten. Verder moet je op de Ubuntu machine wel de juiste cliënt versie hebben (dus zelfde of hoger dan de postgres versie in de timescale addon.

Makes sense?
