### ISSUE TITLE
Error while trying to install Add-on

### ISSUE THREAD

**Issue by BeyondPixels** [sanderdw/hassio-addons#8]
Hello,

First, thanks for the hard work, it seems great!

I was trying to install the Add-on by following the instructions.
I've added the repository, clicked on Install and after some time, I've got an error message asking me to see the logs:
![image](https://user-images.githubusercontent.com/53296978/108697742-87e1b580-7503-11eb-9256-661e81653ce9.png)

It's like it tried to get info from 172.30.32.1 but that it isn't my HA server IP at all...

Thanks in advance for the help.

**Comment by sanderdw** [comment]
Hi, that does not seem like an specific addon error. Can you tell me your hardware en Home Assistant setup and software versions?

Note, 172.30.32.1 are internal ip adresses used by the containers. So that's different from your network adresses.

**Comment by BeyondPixels** [comment]
Sure.
Home Assistant OS 5.11 on RPi 3
core-2021.2.3
supervisor-2021.02.11

I tried to install it again and... it is actually installed !
Weird. I'll continue the setup and will report here if anything goes wrong.
