### ISSUE TITLE
Update to latest version

### ISSUE THREAD

**Issue by erwindouna** [sanderdw/hassio-addons#83]
Currently my version, within the addon, is 12 releases behind. How can I manually update it?

**Comment by sanderdw** [comment]
Hi @erwindouna, which addon exactly? Maybe try a fresh install?

**Comment by erwindouna** [comment]
The DSMR- reader. It seems to be behind in versions. Or is ther another way to keep the DSMR-reader updated within your addon?

**Comment by sanderdw** [comment]
Can you post some screenshots on how you set it up?

**Comment by erwindouna** [comment]
My question is that in your addon the DSMR is still at v5.10.3.
Version 5.11.0 got released 26 days ago. How can we update to this version within the addon?

**Comment by sanderdw** [comment]
Just released it: https://community.home-assistant.io/t/dsmr-reader-add-on-for-home-assistant/279087/408?u=sanderdw
