### ISSUE TITLE
Please downgrade

### ISSUE THREAD

**Issue by erwindouna** [sanderdw/hassio-addons#86]
Please downgrade the docker image to ghcr.io/xirixiz/dsmr-reader-docker:5.11.0-2024.02.04
An [issue ](https://github.com/xirixiz/dsmr-reader-docker/issues/359)has been reported that the data logger is unstable and I am currently also experience this.

**Comment by sanderdw** [comment]
Bssed on the reported issue i created a new release as stability is essential.

**Comment by erwindouna** [comment]
Thanks @sanderdw. I will download this right away and monitor every 10 minutes. I'll keep you posted.

**Comment by erwindouna** [comment]
I can confirm it's still up and running. The data logger still seems to crash, yet it recovers itself and thus no real interference is experienced. In the previous build the data logger did not recovered itself. Maybe the underlying root cause is in DSMR Reader itself?

For now I would say, this it stable on my end. Thanks for your swift action!

```2024-04-17 22:21:41,586 ERROR    mixins       run_once                        107 | dsmr_datalogger.management.commands.dsmr_datalogger: [!] Exception raised. Traceback (most recent call last):
  File "/app/dsmr_backend/mixins.py", line 96, in run_once
    self.run(data=self.data, **options)
  File "/app/dsmr_datalogger/management/commands/dsmr_datalogger.py", line 29, in run
    telegram = next(self.telegram_generator)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dsmr_datalogger/scripts/dsmr_datalogger_api_client.py", line 57, in read_telegram
    incoming_bytes = serial_handle.read(MAX_BYTES_PER_READ)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/serial/serialposix.py", line 595, in read
    raise SerialException(
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)

127.0.0.1 - - [17/Apr/2024:22:21:46 +0200] "GET /about HTTP/1.1" 200 15190 "-" "curl/8.5.0" "-"
Starting DSMR Reader - datalogger...```

**Comment by sanderdw** [comment]
So the thing is in your setup you had already issues? And the 1.11.1 just made it more 'obvious'?

PS i created a 1.1.3 https://github.com/sanderdw/hassio-addons/tree/reader-1.11.3 branch. You copy the dsmr-reder folder mannualy in your addons folder in HA if you want to test again with the new setup (so basicly the 1.11.1 version of the addon.

**Comment by erwindouna** [comment]
Agree. The mitigated solution is that there are indeed better restart mechanics. The root cause should be investigated outside of your add-on solution.
Thanks for your support! I would consider this issue as solved.
