### ISSUE TITLE
DSMR won't start anymore

### ISSUE THREAD

**Issue by scubabas** [sanderdw/hassio-addons#93]
As of yesterday evening, DSMR won't start anymore, no updates done at that time...
Error log:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 

-------------------------
User UID: 0
User GID: 0
-------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-set-app-defaults: executing... 

[ INFO ] DSMR Reader Reader release: 5.11.0

[ INFO ] DSMR Reader Reader Docker release: 2024.02.04

[ INFO ] Ensure permissions...

[ INFO ] Setting architecture requirements...

[ INFO ] ARM Architecture

[ INFO ] Verifying if the DSMR Reader web credential variables have been set...

[ INFO ] Verifying database connectivity to host: dsmrdb with port: 5432...
nc: getaddrinfo for host "dsmrdb" port 5432: Name has no usable address

**Comment by scubabas** [comment]
Yes I do. 

Will try re-install. Thanks

**Comment by scubabas** [comment]
Well, that did the trick. Thanks!

**Comment by DavyRoswinkel** [comment]
Hi,

I have the same issue, reinstalling didn't solve the issue.

Looks like a problem with the hostname of the database.

Even tried the previous version, but got the same issue.
I checked the timescale addon it looks like it's running normally

**Comment by DavyRoswinkel** [comment]
It is back online now. With alot of warnings and hints.
Probably because of the missing connection.
About not enough readings found.

But its running again

**Comment by sanderdw** [comment]
@DavyRoswinkel, so no problems anymore?

Otherwise please drop a copy of the logging here 🙂

**Comment by DavyRoswinkel** [comment]
> @DavyRoswinkel, so no problems anymore?
> 
> Otherwise please drop a copy of the logging here 🙂

No problems anymore
